### ISSUE TITLE
Where is the source code to Gazebo multi-robot simulator, version 7.0.1

### ISSUE THREAD

**Issue by MAVProxyUser** [Parrot-Developers/libpomp#3]
Gazebo multi-robot simulator, version 7.0.1 is a parrot specific version... I would like to recompile it. Where are the deb-src links for apt?

Where is the .tar.gz file for the gazebo code?
```
hg tags | grep _7.0
gazebo7_7.0.0 28214:a29d8dabed9a
gazebo7_7.0.0~pre2 28204:6ae6e198cfd2
gazebo7_7.0.0~pre1 28156:aae2cfd5af69
```

http://forum.developer.parrot.com/t/where-is-the-source-code-to-gazebo-multi-robot-simulator-version-7-0-1/6374

**Comment by ymorgan** [comment]
Not the correct place to ask it, see the answer on the forum

**Comment by MAVProxyUser** [comment]
Please link the answer on the forum.. last I checked you guys had not shared the GPL code, and were blowing people off that asked. 

Send me a direct link to the answer on the forum that has the GPL code.
